apiVersion: v1
kind: Service
metadata:
  name: init-svc
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: init-pod
spec:
  containers:
  - name: nginx
    image: nginx
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c', "until nslookup init-svc.default.svc.cluster.local; do echo waiting for init-svc; sleep 2; done"]