apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec:
  replicas: 3
  selector:
    app: nginx
  template:
    metadata:
      name: nginx-t
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-c
        image: nginx